# Generated by Django 3.2.8 on 2022-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxdoc',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
