# Generated by Django 3.2.8 on 2022-04-27 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePost',
            new_name='QuestionPost',
        ),
    ]
